# 🩺 第十一天 · pandas 入门（DataFrame 表格）

**今天目标（约 1.5 小时）**：用 pandas 读入表格、查看数据、算基础统计。这是你「医学数据岗」技能树的主干。

> 昨日回顾：文件读写、json。今天开始，你处理的不再是几行数据，而是**整张表**。
>
> ⚠️ 开始前先 **Kernel → Restart Kernel**。
>
> 今天的数据：`patients_demo.csv`（16 位患者，已放在本目录）。

## 1. 什么是 pandas / DataFrame

pandas 是 Python 处理**表格数据**的库。它最核心的东西叫 **DataFrame**——可以理解为「Excel 表格」：有行、有列、每列有名字。

惯例：`import pandas as pd`（借进来，简称 pd）。

In [1]:
import pandas as pd

df = pd.read_csv("patients_demo.csv")   # 一行读入 CSV，得到 DataFrame

print(type(df))     # <class 'pandas.core.frame.DataFrame'>
df                   # 直接显示整个表格

<class 'pandas.DataFrame'>

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
0   王小明  45  男  175  82  135  6.2  糖尿病
1   李小红  32  女  162  55  118  5.1  高血压
2    张三  28  男  180  90  142  7.8   肺炎
3    赵四  67  男  168  70  155  6.9  糖尿病
4    孙丽  51  女  158  62  120  5.4   健康
5    钱进  38  男  172  78  130  8.1  糖尿病
6    周杰  74  男  165  58  148  6.5  高血压
7    吴芳  29  女  160  50  110  4.9   健康
8    郑强  43  男  178  85  138  7.2  糖尿病
9    冯梅  60  女  155  66  152  6.8  高血压
10   陈晨  35  男  170  72  125  5.6   肺炎
11   褚蓝  47  女  163  57  116  4.8   健康
12   卫东  58  男  176  80  150  7.5  糖尿病
13   蒋雪  31  女  159  52  108  5.2  高血压
14   沈斌  26  男  182  88  140  6.1   肺炎
15   韩雨  52  女  166  60  122  5.9   健康

## 2. 查看数据的 5 个必学方法

In [2]:
df.head()        # 前 5 行（括号里可写数字，如 head(3)）

    姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
0  王小明  45  男  175  82  135  6.2  糖尿病
1  李小红  32  女  162  55  118  5.1  高血压
2   张三  28  男  180  90  142  7.8   肺炎
3   赵四  67  男  168  70  155  6.9  糖尿病
4   孙丽  51  女  158  62  120  5.4   健康

In [3]:
print(df.shape)       # (行数, 列数)
print(df.columns)     # 所有列名

(16, 8)
Index(['姓名', '年龄', '性别', '身高', '体重', '收缩压', '血糖', '诊断'], dtype='str')

In [4]:
print(df.dtypes)      # 每列的数据类型（object=字符串，int64=整数，float64=小数）

姓名         str
年龄       int64
性别         str
身高       int64
体重       int64
收缩压      int64
血糖     float64
诊断         str
dtype: object

In [5]:
df.info()             # 概览：行列数、每列类型、有无缺失值

<class 'pandas.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      16 non-null     str
 1   年龄      16 non-null     int64
 2   性别      16 non-null     str
 3   身高      16 non-null     int64
 4   体重      16 non-null     int64
 5   收缩压     16 non-null     int64
 6   血糖      16 non-null     float64
 7   诊断      16 non-null     str
dtypes: float64(1), int64(4), str(3)
memory usage: 1.1 KB

## 3. 取一列（得到 Series）

`df["列名"]` 取出一列，变成一个 Series（可以理解成「只有一列的表格」）。

In [6]:
ages = df["年龄"]
print(ages)                 # 一整列
print(type(ages))           # Series

0     45
1     32
2     28
3     67
4     51
5     38
6     74
7     29
8     43
9     60
10    35
11    47
12    58
13    31
14    26
15    52
Name: 年龄, dtype: int64
<class 'pandas.Series'>

### 3.1 对一列做统计（今天核心）

In [7]:
print("平均年龄:", df["年龄"].mean())       # 均值
print("最大年龄:", df["年龄"].max())
print("最小年龄:", df["年龄"].min())
print("中位年龄:", df["年龄"].median())
print("血糖平均值:", df["血糖"].mean())

平均年龄: 44.75
最大年龄: 74
最小年龄: 26
中位年龄: 44.0
血糖平均值: 6.25

In [8]:
df.describe()       # 一次性看所有数值列的统计（count/mean/std/min/四分位/max）

              年龄          身高         体重         收缩压         血糖
count  16.000000   16.000000  16.000000   16.000000  16.000000
mean   44.750000  168.062500  69.062500  131.812500   6.250000
std    14.676512    8.410063  13.388895   15.332835   1.055778
min    26.000000  155.000000  50.000000  108.000000   4.800000
25%    31.750000  161.500000  57.750000  119.500000   5.350000
50%    44.000000  167.000000  68.000000  132.500000   6.150000
75%    53.500000  175.250000  80.500000  143.500000   6.975000
max    74.000000  182.000000  90.000000  155.000000   8.100000

## 4. 计数：value_counts（医学数据超常用）

统计一列里每个值出现了多少次——比如「每种诊断各有多少人」。

In [9]:
df["诊断"].value_counts()      # 每种诊断的人数

诊断
糖尿病    5
高血压    4
健康     4
肺炎     3
Name: count, dtype: int64

In [10]:
df["性别"].value_counts()      # 男女各多少人

性别
男    9
女    7
Name: count, dtype: int64

## 5. 今日练习（必做 6 题）

**练习 1**：读入 `patients_demo.csv` 存到 `df`，用 `head()` 显示前 5 行。

In [11]:
# 在这里写你的代码
import pandas as pd
df=pd.read_csv("patients_demo.csv")
print(df.head())

    姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
0  王小明  45  男  175  82  135  6.2  糖尿病
1  李小红  32  女  162  55  118  5.1  高血压
2   张三  28  男  180  90  142  7.8   肺炎
3   赵四  67  男  168  70  155  6.9  糖尿病
4   孙丽  51  女  158  62  120  5.4   健康

**练习 2**：打印这张表的 `shape`（行数列数）和 `columns`（列名）。

In [15]:
# 在这里写你的代码
print(df.shape)
print(df.columns)

(16, 8)
Index(['姓名', '年龄', '性别', '身高', '体重', '收缩压', '血糖', '诊断'], dtype='str')

**练习 3**：取「血糖」这一列，计算它的平均值、最大值、最小值。

In [16]:
# 在这里写你的代码
glucose=df["血糖"]
print(glucose.mean())
print(glucose.max())
print(glucose.min())

6.25
8.1
4.8

**练习 4**：用 `df.describe()` 查看所有数值列的统计，然后回答：收缩压最高是多少？

In [17]:
# 在这里写你的代码
print(df.describe())

              年龄          身高         体重         收缩压         血糖
count  16.000000   16.000000  16.000000   16.000000  16.000000
mean   44.750000  168.062500  69.062500  131.812500   6.250000
std    14.676512    8.410063  13.388895   15.332835   1.055778
min    26.000000  155.000000  50.000000  108.000000   4.800000
25%    31.750000  161.500000  57.750000  119.500000   5.350000
50%    44.000000  167.000000  68.000000  132.500000   6.150000
75%    53.500000  175.250000  80.500000  143.500000   6.975000
max    74.000000  182.000000  90.000000  155.000000   8.100000

**练习 5（今天的检查点·医学统计）**：用今天学的方法，回答三个问题：

① 这 16 位患者的平均年龄是多少？
② 每种「诊断」各有多少人？
③ 男女各多少人？

每个问题一行代码，写在下面。

In [20]:
# 在这里写你的代码
age=df["年龄"]
print(age.mean())
diagnosis=df["诊断"]
print(diagnosis.value_counts())
print(df["性别"].value_counts())

44.75
诊断
糖尿病    5
高血压    4
健康     4
肺炎     3
Name: count, dtype: int64
性别
男    9
女    7
Name: count, dtype: int64

**练习 6（加分题）**：用 `value_counts()` 统计「诊断」列，然后把结果里的**人数最多**的那个诊断名和人数打印出来。

提示：`value_counts()` 结果里第 1 个就是最多的，可以用 `.index[0]` 和 `.iloc[0]` 取。

In [25]:
# 在这里写你的代码
print(df["诊断"].value_counts())
print(df["诊断"].value_counts().index[0])
print(df["诊断"].value_counts().iloc[0])

诊断
糖尿病    5
高血压    4
健康     4
肺炎     3
Name: count, dtype: int64
糖尿病
5

## ✅ D11 完成标准（打钩）

- [ ] 6 个练习全部跑通
- [ ] 练习 5 能回答三个统计问题
- [ ] 能说出 DataFrame 是什么
- [ ] 保存 notebook（**Cmd + S**）

完成后告诉我，D12 学**筛选与排序**（从表格里挑出想要的行）。

## 📌 今日小抄

读 CSV：`df = pd.read_csv("文件.csv")`

前几行 `df.head()` ｜ 行列数 `df.shape` ｜ 列名 `df.columns`

类型 `df.dtypes` ｜ 概览 `df.info()`

取一列 `df["列名"]`

统计：`mean()` 均值 / `max()` / `min()` / `median()` 中位数

全表统计 `df.describe()` ｜ 计数 `df["列"].value_counts()`