# 🩺 第十二天 · pandas 筛选与排序（从表里挑数据）

**今天目标（约 1.5 小时）**：学会「按条件挑行」和「按列排序」。这是查数据的核心。

> 昨日回顾：读表、看表、算统计。今天学会「从 16 人里挑出符合条件的那些人」。
>
> ⚠️ 开始前先 **Kernel → Restart Kernel**，然后先运行下面这个单元格读入数据。

In [1]:
import pandas as pd
df = pd.read_csv("patients_demo.csv")
df.head()

    姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
0  王小明  45  男  175  82  135  6.2  糖尿病
1  李小红  32  女  162  55  118  5.1  高血压
2   张三  28  男  180  90  142  7.8   肺炎
3   赵四  67  男  168  70  155  6.9  糖尿病
4   孙丽  51  女  158  62  120  5.4   健康

## 1. 布尔筛选：df[条件]

核心思路：写一个「条件」，它对每一行判断 True/False，df[条件] 就只保留 True 的行。

先看条件长什么样：

In [2]:
df["年龄"] > 60        # 每一行判断：年龄是否大于 60 → True/False 一串

0     False
1     False
2     False
3      True
4     False
5     False
6      True
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
Name: 年龄, dtype: bool

In [3]:
# 把条件套进方括号，只保留 True 的行
df[df["年龄"] > 60]

   姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
3  赵四  67  男  168  70  155  6.9  糖尿病
6  周杰  74  男  165  58  148  6.5  高血压

### 1.1 等于：用两个等号 ==

挑出所有「糖尿病」患者：

In [4]:
df[df["诊断"] == "糖尿病"]

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
0   王小明  45  男  175  82  135  6.2  糖尿病
3    赵四  67  男  168  70  155  6.9  糖尿病
5    钱进  38  男  172  78  130  8.1  糖尿病
8    郑强  43  男  178  85  138  7.2  糖尿病
12   卫东  58  男  176  80  150  7.5  糖尿病

### 1.2 不等于：!=（挑出所有「不是健康」的人）

In [5]:
df[df["诊断"] != "健康"]

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
0   王小明  45  男  175  82  135  6.2  糖尿病
1   李小红  32  女  162  55  118  5.1  高血压
2    张三  28  男  180  90  142  7.8   肺炎
3    赵四  67  男  168  70  155  6.9  糖尿病
5    钱进  38  男  172  78  130  8.1  糖尿病
6    周杰  74  男  165  58  148  6.5  高血压
8    郑强  43  男  178  85  138  7.2  糖尿病
9    冯梅  60  女  155  66  152  6.8  高血压
10   陈晨  35  男  170  72  125  5.6   肺炎
12   卫东  58  男  176  80  150  7.5  糖尿病
13   蒋雪  31  女  159  52  108  5.2  高血压
14   沈斌  26  男  182  88  140  6.1   肺炎

## 2. 多个条件：&（且）和 |（或）

⚠️ 两个铁律：
1. 用 `&`（且）、`|`（或），**不是** `and`/`or`；
2. **每个条件都要加括号**。

In [6]:
# 男性 且 糖尿病（两个条件都满足）
df[(df["性别"] == "男") & (df["诊断"] == "糖尿病")]

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
0   王小明  45  男  175  82  135  6.2  糖尿病
3    赵四  67  男  168  70  155  6.9  糖尿病
5    钱进  38  男  172  78  130  8.1  糖尿病
8    郑强  43  男  178  85  138  7.2  糖尿病
12   卫东  58  男  176  80  150  7.5  糖尿病

In [7]:
# 年龄 > 60 或 收缩压 > 150（满足其一即可）
df[(df["年龄"] > 60) | (df["收缩压"] > 150)]

   姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
3  赵四  67  男  168  70  155  6.9  糖尿病
6  周杰  74  男  165  58  148  6.5  高血压
9  冯梅  60  女  155  66  152  6.8  高血压

## 3. isin：属于列表里的值

挑出诊断是「糖尿病」或「高血压」的人（比写两个 == 再 | 更简洁）：

In [8]:
df[df["诊断"].isin(["糖尿病", "高血压"])]

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
0   王小明  45  男  175  82  135  6.2  糖尿病
1   李小红  32  女  162  55  118  5.1  高血压
3    赵四  67  男  168  70  155  6.9  糖尿病
5    钱进  38  男  172  78  130  8.1  糖尿病
6    周杰  74  男  165  58  148  6.5  高血压
8    郑强  43  男  178  85  138  7.2  糖尿病
9    冯梅  60  女  155  66  152  6.8  高血压
12   卫东  58  男  176  80  150  7.5  糖尿病
13   蒋雪  31  女  159  52  108  5.2  高血压

## 4. 排序：sort_values

In [9]:
df.sort_values("收缩压", ascending=False)   # 按收缩压从高到低（False=降序）

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
3    赵四  67  男  168  70  155  6.9  糖尿病
9    冯梅  60  女  155  66  152  6.8  高血压
12   卫东  58  男  176  80  150  7.5  糖尿病
6    周杰  74  男  165  58  148  6.5  高血压
2    张三  28  男  180  90  142  7.8   肺炎
14   沈斌  26  男  182  88  140  6.1   肺炎
8    郑强  43  男  178  85  138  7.2  糖尿病
0   王小明  45  男  175  82  135  6.2  糖尿病
5    钱进  38  男  172  78  130  8.1  糖尿病
10   陈晨  35  男  170  72  125  5.6   肺炎
15   韩雨  52  女  166  60  122  5.9   健康
4    孙丽  51  女  158  62  120  5.4   健康
1   李小红  32  女  162  55  118  5.1  高血压
11   褚蓝  47  女  163  57  116  4.8   健康
7    吴芳  29  女  160  50  110  4.9   健康
13   蒋雪  31  女  159  52  108  5.2  高血压

In [10]:
df.sort_values("年龄")     # 默认升序（从小到大）

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
14   沈斌  26  男  182  88  140  6.1   肺炎
2    张三  28  男  180  90  142  7.8   肺炎
7    吴芳  29  女  160  50  110  4.9   健康
13   蒋雪  31  女  159  52  108  5.2  高血压
1   李小红  32  女  162  55  118  5.1  高血压
10   陈晨  35  男  170  72  125  5.6   肺炎
5    钱进  38  男  172  78  130  8.1  糖尿病
8    郑强  43  男  178  85  138  7.2  糖尿病
0   王小明  45  男  175  82  135  6.2  糖尿病
11   褚蓝  47  女  163  57  116  4.8   健康
4    孙丽  51  女  158  62  120  5.4   健康
15   韩雨  52  女  166  60  122  5.9   健康
12   卫东  58  男  176  80  150  7.5  糖尿病
9    冯梅  60  女  155  66  152  6.8  高血压
3    赵四  67  男  168  70  155  6.9  糖尿病
6    周杰  74  男  165  58  148  6.5  高血压

## 5. 今日练习（必做 6 题）

**练习 1**：挑出所有「高血压」患者。

In [11]:
# 在这里写你的代码
df[df["诊断"]=="高血压"]

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
1   李小红  32  女  162  55  118  5.1  高血压
6    周杰  74  男  165  58  148  6.5  高血压
9    冯梅  60  女  155  66  152  6.8  高血压
13   蒋雪  31  女  159  52  108  5.2  高血压

**练习 2**：挑出年龄 ≥ 60 的患者。

In [12]:
# 在这里写你的代码
df[df["年龄"]>=60]

   姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
3  赵四  67  男  168  70  155  6.9  糖尿病
6  周杰  74  男  165  58  148  6.5  高血压
9  冯梅  60  女  155  66  152  6.8  高血压

**练习 3**：挑出所有女性患者。

In [13]:
# 在这里写你的代码
df[df["性别"]=="女"]

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
1   李小红  32  女  162  55  118  5.1  高血压
4    孙丽  51  女  158  62  120  5.4   健康
7    吴芳  29  女  160  50  110  4.9   健康
9    冯梅  60  女  155  66  152  6.8  高血压
11   褚蓝  47  女  163  57  116  4.8   健康
13   蒋雪  31  女  159  52  108  5.2  高血压
15   韩雨  52  女  166  60  122  5.9   健康

**练习 4**：挑出「糖尿病 且 年龄 ≥ 60」的患者（组合条件，记得加括号）。

In [15]:
# 在这里写你的代码
df[(df["诊断"]=="糖尿病") & (df["年龄"]>=60)]

   姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
3  赵四  67  男  168  70  155  6.9  糖尿病

**练习 5（今天的检查点·查数据）**：挑出「收缩压 > 140」的患者，并按收缩压从高到低排序。

In [16]:
# 在这里写你的代码
df[df["收缩压"]>140].sort_values("收缩压", ascending=False)

    姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
3   赵四  67  男  168  70  155  6.9  糖尿病
9   冯梅  60  女  155  66  152  6.8  高血压
12  卫东  58  男  176  80  150  7.5  糖尿病
6   周杰  74  男  165  58  148  6.5  高血压
2   张三  28  男  180  90  142  7.8   肺炎

**练习 6（加分题）**：用 `isin` 挑出诊断属于 `["高血压", "肺炎"]` 的患者。

In [19]:
# 在这里写你的代码
df[df ["诊断"].isin(["高血压","肺炎"])]

     姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
1   李小红  32  女  162  55  118  5.1  高血压
2    张三  28  男  180  90  142  7.8   肺炎
6    周杰  74  男  165  58  148  6.5  高血压
9    冯梅  60  女  155  66  152  6.8  高血压
10   陈晨  35  男  170  72  125  5.6   肺炎
13   蒋雪  31  女  159  52  108  5.2  高血压
14   沈斌  26  男  182  88  140  6.1   肺炎

## ✅ D12 完成标准（打钩）

- [ ] 6 个练习全部跑通
- [ ] 练习 5 能筛选+排序
- [ ] 能说出 & 和 | 的用法
- [ ] 保存 notebook（**Cmd + S**）

完成后告诉我，D13 学**分组与聚合**（groupby），那是 pandas 最后一块拼图。

## 📌 今日小抄

挑行：`df[条件]`

等于 `==` ｜ 不等于 `!=` ｜ 大于 `>` ｜ 大于等于 `>=`

且 `&` ｜ 或 `|`（每个条件加括号）

属于列表 `df["列"].isin([...])`

排序 `df.sort_values("列", ascending=False)`（False 降序）