# 🩺 第十三天 · pandas 分组聚合（groupby）

**今天目标（约 1.5 小时）**：按组统计——「不同诊断患者的平均年龄」「男女平均收缩压」这类问题。这是 pandas 最后一块拼图。

> 昨日回顾：筛选、排序。今天学「分组后算统计」。
>
> ⚠️ 先 **Kernel → Restart Kernel**，然后运行下面单元格读数据。

In [1]:
import pandas as pd
df = pd.read_csv("patients_demo.csv")
df.head()

    姓名  年龄 性别   身高  体重  收缩压   血糖   诊断
0  王小明  45  男  175  82  135  6.2  糖尿病
1  李小红  32  女  162  55  118  5.1  高血压
2   张三  28  男  180  90  142  7.8   肺炎
3   赵四  67  男  168  70  155  6.9  糖尿病
4   孙丽  51  女  158  62  120  5.4   健康

## 1. groupby 是什么

`groupby("某列")` = 「按某列分组」。分组后就能对**每一组**分别算统计。

最经典的写法（分三步读）：

```python
df.groupby("诊断")["年龄"].mean()
```

1. `df.groupby("诊断")`：按「诊断」分组（糖尿病一组、高血压一组…）；
2. `["年龄"]`：每组里，只看「年龄」这一列；
3. `.mean()`：每组的年龄求平均。

In [2]:
df.groupby("诊断")["年龄"].mean()    # 每种诊断的平均年龄

诊断
健康     44.750000
糖尿病    50.200000
肺炎     29.666667
高血压    49.250000
Name: 年龄, dtype: float64

## 2. 常用的几种聚合

`mean`（均值）、`count`（人数）、`max`、`min`、`median`（中位数）、`sum`。

In [3]:
df.groupby("诊断")["年龄"].count()     # 每种诊断各有多少人

诊断
健康     4
糖尿病    5
肺炎     3
高血压    4
Name: 年龄, dtype: int64

In [4]:
df.groupby("性别")["收缩压"].mean()    # 男女平均收缩压

性别
女    120.857143
男    140.333333
Name: 收缩压, dtype: float64

In [5]:
df.groupby("诊断")["血糖"].max()      # 每种诊断里血糖的最高值

诊断
健康     5.9
糖尿病    8.1
肺炎     7.8
高血压    6.8
Name: 血糖, dtype: float64

## 3. agg：一次算多个统计

想同时看「每组的人数 + 平均年龄」，用 `agg` 传一个列表：

In [6]:
df.groupby("诊断")["年龄"].agg(["count", "mean"])

     count       mean
诊断
健康       4  44.750000
糖尿病      5  50.200000
肺炎       3  29.666667
高血压      4  49.250000

In [7]:
df.groupby("诊断")["收缩压"].agg(["mean", "max", "min"])

           mean  max  min
诊断
健康   117.000000  122  110
糖尿病  141.600000  155  130
肺炎   135.666667  142  125
高血压  131.500000  152  108

## 4. 今日练习（必做 6 题）

**练习 1**：按「诊断」分组，算每组平均年龄。

In [8]:
# 在这里写你的代码
df.groupby("诊断")["年龄"].mean()

诊断
健康     44.750000
糖尿病    50.200000
肺炎     29.666667
高血压    49.250000
Name: 年龄, dtype: float64

**练习 2**：按「诊断」分组，算每组人数（`count`）。

In [12]:
# 在这里写你的代码
df.groupby("诊断")["性别"].count()

诊断
健康     4
糖尿病    5
肺炎     3
高血压    4
Name: 性别, dtype: int64

**练习 3**：按「性别」分组，算平均收缩压。

In [14]:
# 在这里写你的代码
df.groupby("性别")["收缩压"].mean()

性别
女    120.857143
男    140.333333
Name: 收缩压, dtype: float64

**练习 4**：按「诊断」分组，算每组的血糖最大值。

In [15]:
# 在这里写你的代码
df.groupby("诊断")["血糖"].max()

诊断
健康     5.9
糖尿病    8.1
肺炎     7.8
高血压    6.8
Name: 血糖, dtype: float64

**练习 5（今天的检查点·agg）**：按「诊断」分组，用 `agg` 一次算「人数 + 平均年龄」。

In [17]:
# 在这里写你的代码
df.groupby("诊断")["年龄"].agg(["count","mean"])

     count       mean
诊断
健康       4  44.750000
糖尿病      5  50.200000
肺炎       3  29.666667
高血压      4  49.250000

**练习 6（加分题）**：按「性别」分组，用 `agg` 算血糖的「均值 + 中位数」两个统计。

In [18]:
# 在这里写你的代码
df.groupby("性别")["血糖"].agg(["mean","median"])

        mean  median
性别
女   5.442857     5.2
男   6.877778     6.9

## ✅ D13 完成标准（打钩）

- [ ] 6 个练习全部跑通
- [ ] 练习 5 能一次算多个统计
- [ ] 能说出 groupby 的写法结构
- [ ] 保存 notebook（**Cmd + S**）

完成后告诉我，D14 是**第二周复盘**：把本周成果推 GitHub + 写周报。

## 📌 今日小抄

分组统计：`df.groupby("分组列")["统计列"].聚合()`

均值 `.mean()` ｜ 人数 `.count()` ｜ 最大 `.max()` ｜ 最小 `.min()` ｜ 中位数 `.median()`

一次算多个：`.agg(["count", "mean"])`

读法：按 X 分组 → 看 Y 列 → 算 Z