# 🩺 第十五天 · pandas merge 合并 + 缺失值处理

**今天目标（约 1.5 小时）**：学会把两张表「按姓名对齐」合并成一张，并处理缺失数据。这是真实数据工作每天都会遇到的事。

> 昨日回顾：筛选、排序、分组。今天补齐 pandas 最后两个高频技能：**合并**和**缺失值**。
>
> ⚠️ 先 **Kernel → Restart Kernel**。
>
> 数据：`patients_base.csv`（8 人基本信息）+ `patients_labs.csv`（6 人检验结果，含缺失值）。

In [2]:
import pandas as pd

base = pd.read_csv("patients_base.csv")
labs = pd.read_csv("patients_labs.csv")

print("基本信息表:")
print(base)
print("\n检验结果表:")
print(labs)

基本信息表:
    姓名  年龄 性别
0  王小明  45  男
1  李小红  32  女
2   张三  28  男
3   赵四  67  男
4   孙丽  51  女
5   钱进  38  男
6   周杰  74  男
7   吴芳  29  女

检验结果表:
    姓名   WBC   血糖
0  王小明   4.2  6.2
1  李小红   NaN  5.1
2   张三  12.1  NaN
3   赵四   2.8  6.9
4   孙丽   7.5  5.4
5   郑强   6.0  7.2

## 1. merge：像 Excel 的 VLOOKUP 一样对齐两张表

`pd.merge(左表, 右表, on="对齐用的列", how="方式")`

`how` 四种方式（先只记前两种）：
- `"inner"`：只保留**两边都有的**人（交集）
- `"left"`：保留左表**所有人**，右边对不上的填空（最常用！）

In [12]:
# inner：两边都有的人 → 郑强(只在labs)、钱进/周杰/吴芳(只在base)都会消失
merged_inner = pd.merge(base, labs, on="姓名", how="inner")
merged_inner

    姓名  年龄 性别   WBC   血糖
0  王小明  45  男   4.2  6.2
1  李小红  32  女   NaN  5.1
2   张三  28  男  12.1  NaN
3   赵四  67  男   2.8  6.9
4   孙丽  51  女   7.5  5.4

In [3]:
# left：保留 base 所有人，labs 里没有的补成 NaN
merged_left = pd.merge(base, labs, on="姓名", how="left")
merged_left

    姓名  年龄 性别   WBC   血糖
0  王小明  45  男   4.2  6.2
1  李小红  32  女   NaN  5.1
2   张三  28  男  12.1  NaN
3   赵四  67  男   2.8  6.9
4   孙丽  51  女   7.5  5.4
5   钱进  38  男   NaN  NaN
6   周杰  74  男   NaN  NaN
7   吴芳  29  女   NaN  NaN

**结论**：`inner` = 只留交集；`left` = 左表为主（患者都要在，缺检验就是缺检验）。

（另外两种：`right` = 右表为主；`outer` = 两边全留。用到再查。）

## 2. 缺失值：先查，再处理

### 2.1 查缺失：isnull / isna

In [4]:
print("每列有多少缺失值：")
print(merged_left.isnull().sum())     # 每列缺失计数

每列有多少缺失值：
姓名     0
年龄     0
性别     0
WBC    4
血糖     4
dtype: int64

In [9]:
merged_left[merged_left["WBC"].isnull()]   # 挑出 WBC 缺失的行

    姓名  年龄 性别  WBC   血糖
1  李小红  32  女  NaN  5.1
5   钱进  38  男  NaN  NaN
6   周杰  74  男  NaN  NaN
7   吴芳  29  女  NaN  NaN

### 2.2 处理缺失：dropna 删 / fillna 填

三种常用策略：① 删除有缺失的行；② 用均值/中位数填；③ 用指定值填（如填「未测」）。

In [6]:
# ① 删掉任何一列有缺失的行
merged_left.dropna()

    姓名  年龄 性别  WBC   血糖
0  王小明  45  男  4.2  6.2
3   赵四  67  男  2.8  6.9
4   孙丽  51  女  7.5  5.4

In [10]:
# ② 用每列的均值填充（医学数据常用）
filled = merged_left.copy()
filled["WBC"] = filled["WBC"].fillna(filled["WBC"].mean())
filled["血糖"] = filled["血糖"].fillna(filled["血糖"].mean())
filled

    姓名  年龄 性别    WBC   血糖
0  王小明  45  男   4.20  6.2
1  李小红  32  女   6.65  5.1
2   张三  28  男  12.10  5.9
3   赵四  67  男   2.80  6.9
4   孙丽  51  女   7.50  5.4
5   钱进  38  男   6.65  5.9
6   周杰  74  男   6.65  5.9
7   吴芳  29  女   6.65  5.9

In [11]:
# ③ 用指定值填（比如性别缺失填「未知」）
merged_left["性别"] = merged_left["性别"].fillna("未知")
merged_left.head()

    姓名  年龄 性别   WBC   血糖
0  王小明  45  男   4.2  6.2
1  李小红  32  女   NaN  5.1
2   张三  28  男  12.1  NaN
3   赵四  67  男   2.8  6.9
4   孙丽  51  女   7.5  5.4

## 3. 今日练习（必做 6 题）

> 先重新读数据：`base = pd.read_csv("patients_base.csv")`、`labs = pd.read_csv("patients_labs.csv")`

**练习 1**：用 `how="inner"` 按姓名合并两张表，打印结果，数一数剩几行。

In [6]:
# 在这里写你的代码
import pandas as pd
base = pd.read_csv("patients_base.csv")
labs = pd.read_csv("patients_labs.csv")
merged_inner=pd.merge(base, labs, on="姓名", how="inner")
merged_inner

    姓名  年龄 性别   WBC   血糖
0  王小明  45  男   4.2  6.2
1  李小红  32  女   NaN  5.1
2   张三  28  男  12.1  NaN
3   赵四  67  男   2.8  6.9
4   孙丽  51  女   7.5  5.4

**练习 2**：用 `how="left"` 以 base 为主合并，打印结果，指出哪些人是 NaN。

In [7]:
# 在这里写你的代码
merged_left=pd.merge(base, labs, on="姓名", how="left")
merged_left

    姓名  年龄 性别   WBC   血糖
0  王小明  45  男   4.2  6.2
1  李小红  32  女   NaN  5.1
2   张三  28  男  12.1  NaN
3   赵四  67  男   2.8  6.9
4   孙丽  51  女   7.5  5.4
5   钱进  38  男   NaN  NaN
6   周杰  74  男   NaN  NaN
7   吴芳  29  女   NaN  NaN

**练习 3**：对练习 2 的结果，用 `isnull().sum()` 统计每列的缺失数。

In [8]:
# 在这里写你的代码
print(merged_left.isnull().sum())

姓名     0
年龄     0
性别     0
WBC    4
血糖     4
dtype: int64

**练习 4**：对练习 2 的结果做 `dropna()`，看看还剩几行、剩下的是谁。

In [9]:
# 在这里写你的代码
merged_left.dropna()

    姓名  年龄 性别  WBC   血糖
0  王小明  45  男  4.2  6.2
3   赵四  67  男  2.8  6.9
4   孙丽  51  女  7.5  5.4

**练习 5（今天的检查点）**：left 合并后，把 WBC 和血糖的缺失值都填成**该列的中位数**，然后打印处理后的表。

提示：`median()` 用法和 `mean()` 一样。

In [14]:
# 在这里写你的代码
fill=merged_left.copy()
fill["WBC"]=fill["WBC"].fillna(fill["WBC"].median())
fill["血糖"]=fill["血糖"].fillna(fill["血糖"].median())
fill

    姓名  年龄 性别    WBC   血糖
0  王小明  45  男   4.20  6.2
1  李小红  32  女   5.85  5.1
2   张三  28  男  12.10  5.8
3   赵四  67  男   2.80  6.9
4   孙丽  51  女   7.50  5.4
5   钱进  38  男   5.85  5.8
6   周杰  74  男   5.85  5.8
7   吴芳  29  女   5.85  5.8

**练习 6（加分题）**：用 `how="outer"` 合并两张表（两边全保留），统计结果多少行，看看谁只出现在一边。

In [13]:
# 在这里写你的代码
merged_outer=pd.merge(base,labs, on="姓名",how="outer")
merged_outer

    姓名    年龄   性别   WBC   血糖
0   吴芳  29.0    女   NaN  NaN
1   周杰  74.0    男   NaN  NaN
2   孙丽  51.0    女   7.5  5.4
3   张三  28.0    男  12.1  NaN
4  李小红  32.0    女   NaN  5.1
5  王小明  45.0    男   4.2  6.2
6   赵四  67.0    男   2.8  6.9
7   郑强   NaN  NaN   6.0  7.2
8   钱进  38.0    男   NaN  NaN

## ✅ D15 完成标准（打钩）

- [ ] 6 个练习全部跑通
- [ ] 能说出 inner 和 left 的区别
- [ ] 会用 isnull / dropna / fillna
- [ ] 保存 notebook（**Cmd + S**）

完成后告诉我，D16 是 **pandas 实战日**：用真实公开数据集跑完整分析。

## 📌 今日小抄

合并：`pd.merge(左, 右, on="键列", how="inner/left/right/outer")`

inner = 两边都有 ｜ left = 左表为主 ｜ outer = 全保留

查缺失：`df.isnull()` / `df.isnull().sum()`

删缺失行：`df.dropna()`

填缺失：`df["列"].fillna(值)` ｜ 填均值 `fillna(df["列"].mean())`

改原表先 `copy()`：`filled = df.copy()`