# 🏆 第二十天 · 核心作品：设计《医学问答评测集》

**今天目标（约 2 小时）**：设计一份 50 题的医学问答评测集 + 打分标准。这是你求职作品集里最硬的一块砖。

**作品定位**：一份「用来给医疗大模型打分」的题目集——面试时你可以说：『我自己设计并跑通了一个 50 题的医疗 LLM 评测集』。

> ⚠️ 先 **Kernel → Restart Kernel**。
>
> 今天只设计题目（D21 跑评测、算分、写报告）。

## 1. 评测集规格（先定标准，再出题）

| 项目 | 规格 |
|---|---|
| 名称 | 医学大模型基础能力评测集 v1（MedQA-Eval v1） |
| 题量 | 50 题（可先做 40） |
| 题型 | **单选题**（4 个选项、唯一标准答案——客观题便于算准确率） |
| 维度 | 4 类：诊断 / 用药 / 指南 / 伦理 |
| 每维度 | 约 12-13 题 |
| 题目来源 | 执业医师真题改编、教材（人卫版）、临床指南 |
| 每题要求 | 你**自己能确认**标准答案正确 + 有出处 |

## 2. 打分标准（明天跑评测时用，今天先定好）

客观题打两项分，每题满分 10 分：

| 评分项 | 分值 | 标准 |
|---|---|---|
| **正确性** | 6 分 | 选对 6 分；选错 0 分 |
| **依据质量** | 4 分 | 给了正确出处/依据 4 分；依据错误或编造 0 分；没给 2 分 |

> 依据质量是**你独有的设计**：通用评测只判对错，你额外要求模型"给依据"——这样能同时测出 D17 发现的**幻觉**问题。面试讲这个设计，非常加分。

## 3. 出题工作台（重要：先看示例再动笔）

题目存在一个「字典的列表」里，每道题 8 个字段：`题号 / 维度 / 题目 / A / B / C / D / 答案`。

**先运行这个示例（2 道题），看懂结构**：

In [ ]:
import pandas as pd

questions = [
    {
        "题号": 1,
        "维度": "诊断",
        "题目": "患者突发胸骨后压榨性疼痛 30 分钟，含服硝酸甘油不缓解，最可能的诊断是？",
        "A": "稳定型心绞痛",
        "B": "急性心肌梗死",
        "C": "主动脉夹层",
        "D": "急性心包炎",
        "答案": "B",
    },
    {
        "题号": 2,
        "维度": "用药",
        "题目": "2 型糖尿病一线首选口服降糖药是？",
        "A": "格列美脲",
        "B": "二甲双胍",
        "C": "阿卡波糖",
        "D": "达格列净",
        "答案": "B",
    },
]

df = pd.DataFrame(questions)
df

## 4. 你的题目（练习：四个维度，分 4 个单元格写）

**写题规则**：
1. 每题必须**你自己能立刻确认答案**（吃不准的题不写）；
2. 可以改编执医真题/教材，**换掉题干措辞**即可；
3. 4 个选项里正确答案位置要**打散**（别全是 B）；
4. 可以用 DeepSeek 帮你草拟题目，但**每题的答案必须由你核验**（它出的题答案可能错，你核验 = 练习 D17 的能力）。

### 练习 1：诊断维度（12 题）

复制上面的字典格式，把 `questions` 换成 `q_diag = [...]`，写 12 道诊断题。

In [3]:
# 在这里写你的代码（q_diag = [...]）
import pandas as pd
q_diag=[
    {
        "题号":1,
        "维度":"诊断",
        "题目": "患者突发胸骨后压榨性疼痛 30 分钟，含服硝酸甘油不缓解，最可能的诊断是？",
        "A": "稳定型心绞痛",
        "B": "急性心肌梗死",
        "C": "主动脉夹层",
        "D": "急性心包炎",
        "答案": "B",
    },
    {
        "题号": 2,
        "维度": "诊断",
        "题目": "对阻塞性肺气肿的诊断，最有价值的是？",
        "A": "PaO2<正常",
        "B": "潮气量低于正常",
        "C": "残气量/肺总量>40%",
        "D": "PaCO2>正常",
        "答案": "C",
    },
    {
        "题号": 3,
        "维度": "诊断",
        "题目": "最易发生左心功能不全临床表现的心脏瓣膜病是",
        "A": "主动脉狭窄",
        "B": "主动脉关闭不全",
        "C": "二尖瓣狭窄",
        "D": "二尖瓣关闭不全",
        "答案": "C",
    },
    {
        "题号": 4,
        "维度": "诊断",
        "题目": "诊断反流性食管炎最准确的方法是",
        "A": "食管内镜检查",
        "B": "食管吞钡X线检查",
        "C": "食管滴酸试验",
        "D": "食管测压",
        "答案": "A",
    },
    {
        "题号": 5,
        "维度": "诊断",
        "题目": "患者男，32岁，周期性上腹痛三年，空腹发作，夜间更重，进食可缓解，服西咪替丁可止痛，最可能的诊断是",
        "A": "十二指肠溃疡",
        "B": "胃溃疡",
        "C": "慢性胃炎",
        "D": "胃食管反流病",
        "答案": "A",
    },
    {
        "题号": 6,
        "维度": "诊断",
        "题目": "下列描述中哪项不正确",
        "A": "每日尿量<100ml为无尿",
        "B": "每日尿蛋白量持续>150mg为蛋白尿",
        "C": "12小时尿红细胞计数>50万为镜下血尿",
        "D": "12小时尿沉渣计数管型>1万为管型尿",
        "答案": "D",
    },
    {
        "题号": 7,
        "维度": "诊断",
        "题目": "对高度怀疑肠结核病例中，下列最有利于临床诊断的是",
        "A": "抗结核治疗2-6周有效",
        "B": "PPD试验阳性",
        "C": "有肠外结核",
        "D": "有腹痛，腹泻，右下腹压痛",
        "答案": "A",
    },
    {
        "题号": 8,
        "维度": "诊断",
        "题目": "Crohn病与肠结核最主要的鉴别点是",
        "A": "病程长短",
        "B": "有无肠外结核",
        "C": "OT试验是否阳性",
        "D": "病理检查有无干酪坏死",
        "答案": "D",
    },
    {
        "题号": 9,
        "维度": "诊断",
        "题目": "肾小球源性血尿最常见的病因是",
        "A": "急性肾小球肾炎",
        "B": "慢性肾小球肾炎",
        "C": "急性肾盂肾炎",
        "D": "IgA肾病",
        "答案": "D",
    },    
    {
        "题号": 10,
        "维度": "诊断",
        "题目": "缺铁性贫血诊断的最可靠依据是",
        "A": "血红蛋白及骨髓储存铁均减少",
        "B": "小细胞性贫血",
        "C": "小细胞低色素性贫血",
        "D": "骨髓增生性贫血",
        "答案": "A",
    },
    {
        "题号": 11,
        "维度": "诊断",
        "题目": "下列急性白血病患者的白血病细胞镜检时，无Auer小体的类型是",
        "A": "急性淋巴细胞白血病",
        "B": "急性早幼粒细胞白血病",
        "C": "急性单核细胞白血病",
        "D": "急性粒细胞白血病部分分化型",
        "答案": "A",
    },    
    {
        "题号": 12,
        "维度": "诊断",
        "题目": "放射性核素主要用于诊断的病症是",
        "A": "肺泡炎",
        "B": "肺栓塞",
        "C": "结节病",
        "D": "肺泡内出血",
        "答案": "B",
    }, 
]

df = pd.DataFrame(q_diag)
df

,题号,维度,题目,A,B,C,D,答案
0,1,诊断,患者突发胸骨后压榨性疼痛 30 分钟，含服硝酸甘油不缓解，最可能的诊断是？,稳定型心绞痛,急性心肌梗死,主动脉夹层,急性心包炎,B
1,2,诊断,对阻塞性肺气肿的诊断，最有价值的是？,PaO2<正常,潮气量低于正常,残气量/肺总量>40%,PaCO2>正常,C
2,3,诊断,最易发生左心功能不全临床表现的心脏瓣膜病是,主动脉狭窄,主动脉关闭不全,二尖瓣狭窄,二尖瓣关闭不全,C
3,4,诊断,诊断反流性食管炎最准确的方法是,食管内镜检查,食管吞钡X线检查,食管滴酸试验,食管测压,A
4,5,诊断,患者男，32岁，周期性上腹痛三年，空腹发作，夜间更重，进食可缓解，服西咪替丁可止痛，最可能的诊断是,十二指肠溃疡,胃溃疡,慢性胃炎,胃食管反流病,A
5,6,诊断,下列描述中哪项不正确,每日尿量<100ml为无尿,每日尿蛋白量持续>150mg为蛋白尿,12小时尿红细胞计数>50万为镜下血尿,12小时尿沉渣计数管型>1万为管型尿,D
6,7,诊断,对高度怀疑肠结核病例中，下列最有利于临床诊断的是,抗结核治疗2-6周有效,PPD试验阳性,有肠外结核,有腹痛，腹泻，右下腹压痛,A
7,8,诊断,Crohn病与肠结核最主要的鉴别点是,病程长短,有无肠外结核,OT试验是否阳性,病理检查有无干酪坏死,D
8,9,诊断,肾小球源性血尿最常见的病因是,急性肾小球肾炎,慢性肾小球肾炎,急性肾盂肾炎,IgA肾病,D
9,10,诊断,缺铁性贫血诊断的最可靠依据是,血红蛋白及骨髓储存铁均减少,小细胞性贫血,小细胞低色素性贫血,骨髓增生性贫血,A
10,11,诊断,下列急性白血病患者的白血病细胞镜检时，无Auer小体的类型是,急性淋巴细胞白血病,急性早幼粒细胞白血病,急性单核细胞白血病,急性粒细胞白血病部分分化型,A
11,12,诊断,放射性核素主要用于诊断的病症是,肺泡炎,肺栓塞,结节病,肺泡内出血,B

### 练习 2：用药维度（12 题）

In [4]:
# 在这里写你的代码（q_drug = [...]）
q_drug=[
    {
        "题号":1,
        "维度":"用药",
        "题目": "阿片类麻醉药的解毒药",
        "A": "依地酸二钠钙",
        "B": "亚甲蓝",
        "C": "纳洛酮",
        "D": "氟马西尼",
        "答案": "C",
    },
    {
        "题号":2,
        "维度":"用药",
        "题目": "下列药物属于治疗风湿病情的药物是",
        "A": "阿司匹林",
        "B": "环孢素",
        "C": "醋酸泼尼松",
        "D": "塞来昔布",
        "答案": "B",
    },
    {
        "题号":3,
        "维度":"用药",
        "题目": "环磷酰胺属于化疗药物的",
        "A": "细胞毒素类",
        "B": "抗代谢类",
        "C": "抗生素类",
        "D": "生物碱类",
        "答案": "A",
    },
    {
        "题号":4,
        "维度":"用药",
        "题目": "亚硝酸盐中毒的解毒药是",
        "A": "依地酸二钠钙",
        "B": "亚甲蓝",
        "C": "二巯基丁二钠",
        "D": "纳洛酮",
        "答案": "B",
    },
    {
        "题号":5,
        "维度":"用药",
        "题目": "氟尿嘧啶属于化疗药物的",
        "A": "细胞毒素类",
        "B": "抗代谢类",
        "C": "抗生素类",
        "D": "生物碱类",
        "答案": "B",
    },
    {
        "题号":6,
        "维度":"用药",
        "题目": "适合于分娩镇痛的局麻药是",
        "A": "利多卡因",
        "B": "丁卡因",
        "C": "普鲁卡因",
        "D": "布比卡因",
        "答案": "D",
    },
    {
        "题号":7,
        "维度":"用药",
        "题目": "对结核菌有抑菌作用的药物是",
        "A": "对氨基水杨酸钠",
        "B": "乙胺丁醇",
        "C": "二者皆是",
        "D": "二者皆非",
        "答案": "C",
    },
    {
        "题号":8,
        "维度":"用药",
        "题目": "最适用于神经阻滞的局麻药是",
        "A": "普鲁卡因",
        "B": "利多卡因",
        "C": "布比卡因",
        "D": "丁卡因",
        "答案": "B",
    },
    {
        "题号":9,
        "维度":"用药",
        "题目": "误服下列哪种药物应禁忌洗胃",
        "A": "东莨菪碱",
        "B": "水杨酸盐",
        "C": "氢氧化钠",
        "D": "盐酸麻黄碱",
        "答案": "C",
    },
    {
        "题号":10,
        "维度":"用药",
        "题目": "用药物破坏动物胰岛β细胞后",
        "A": "血管平滑肌对儿茶酚胺的反应性降低",
        "B": "体内水潴留",
        "C": "ACTH降低",
        "D": "血糖水平升高",
        "答案": "D",
    },
    {
        "题号":11,
        "维度":"用药",
        "题目": "苯二氮卓类中毒的有效解毒药",
        "A": "氟马西尼",
        "B": "亚硝酸异戊酯",
        "C": "二巯丙磺钠",
        "D": "亚甲蓝",
        "答案": "A",
    },
    {
        "题号":12,
        "维度":"用药",
        "题目": "治疗支气管哮喘的缓解药物不包括",
        "A": "速效吸入的β2受体激动剂",
        "B": "短效茶碱",
        "C": "白三烯调节剂",
        "D": "全身用糖皮质激素",
        "答案": "C",
    },
]
df = pd.DataFrame(q_drug)
df

    题号  维度                题目                 A       B       C         D 答案
0    1  用药        阿片类麻醉药的解毒药            依地酸二钠钙     亚甲蓝     纳洛酮      氟马西尼  C
1    2  用药  下列药物属于治疗风湿病情的药物是              阿司匹林     环孢素   醋酸泼尼松      塞来昔布  B
2    3  用药       环磷酰胺属于化疗药物的             细胞毒素类    抗代谢类    抗生素类      生物碱类  A
3    4  用药       亚硝酸盐中毒的解毒药是            依地酸二钠钙     亚甲蓝  二巯基丁二钠       纳洛酮  B
4    5  用药       氟尿嘧啶属于化疗药物的             细胞毒素类    抗代谢类    抗生素类      生物碱类  B
5    6  用药      适合于分娩镇痛的局麻药是              利多卡因     丁卡因    普鲁卡因      布比卡因  D
6    7  用药     对结核菌有抑菌作用的药物是           对氨基水杨酸钠    乙胺丁醇    二者皆是      二者皆非  C
7    8  用药     最适用于神经阻滞的局麻药是              普鲁卡因    利多卡因    布比卡因       丁卡因  B
8    9  用药     误服下列哪种药物应禁忌洗胃              东莨菪碱    水杨酸盐    氢氧化钠     盐酸麻黄碱  C
9   10  用药     用药物破坏动物胰岛β细胞后  血管平滑肌对儿茶酚胺的反应性降低   体内水潴留  ACTH降低    血糖水平升高  D
10  11  用药     苯二氮卓类中毒的有效解毒药              氟马西尼  亚硝酸异戊酯   二巯丙磺钠       亚甲蓝  A
11  12  用药   治疗支气管哮喘的缓解药物不包括      速效吸入的β2受体激动剂    短效茶碱  白三烯调节剂  全身用糖皮质激素  C

### 练习 3：指南维度（12 题）

出「指南推荐」类题（如高血压分级、他汀目标值、疫苗接种等有明确指南依据的）。

In [5]:
# 在这里写你的代码（q_guideline = [...]）
q_guideline=[
    {
        "题号":1,
        "维度":"指南",
        "题目": "根据《中国高血压防治指南（2024年修订版）》，下列哪种情况可诊断高血压？",
        "A": "诊室血压≥130/80 mmHg",
        "B": "家庭自测血压≥135/85 mmHg",
        "C": "24小时动态血压平均值≥140/90 mmHg",
        "D": "仅凭单次诊室血压≥140/90 mmHg",
        "答案": "B",
        "出处": "中国高血压防治指南(2024年修订版)，中华高血压杂志2024年第7期",
    },
    {
        "题号":2,
        "维度":"指南",
        "题目": "根据2024年中国高血压防治指南，一般高血压患者的降压治疗目标是？",
        "A": "诊室血压<140/90 mmHg，如能耐受降至<130/80 mmHg",
        "B": "一律降至<130/80 mmHg",
        "C": "老年人一律<150/90 mmHg",
        "D": "一律降至<120/80 mmHg",
        "答案": "A",
        "出处": "中国高血压防治指南(2024年修订版)",
    },
    {
        "题号":3,
        "维度":"指南",
        "题目": "根据《中国血脂管理指南（2023年）》，ASCVD 极高危患者的 LDL-C 控制目标为？",
        "A": "<3.4 mmol/L",
        "B": "<2.6 mmol/L",
        "C": "<1.4 mmol/L 且较基线降低>50%",
        "D": "<1.8 mmol/L 且较基线降低>50%",
        "答案": "D",
        "出处": "中国血脂管理指南(2023年)，中国循环杂志2023;38(3)",
    },
    {
        "题号":4,
        "维度":"指南",
        "题目": "根据《中国血脂管理指南（2023年）》，ASCVD 超高危患者的 LDL-C 控制目标为？",
        "A": "<3.4 mmol/L",
        "B": "<2.6 mmol/L",
        "C": "<1.4 mmol/L 且较基线降低>50%",
        "D": "<1.8 mmol/L 且较基线降低>50%",
        "答案": "C",
        "出处": "中国血脂管理指南(2023年)",
    },
    {
        "题号":5,
        "维度":"指南",
        "题目": "根据《中国2型糖尿病防治指南（2020年版）》，一般成人2型糖尿病患者的 HbA1c 控制目标为？",
        "A": "<6.0%",
        "B": "<7.0%",
        "C": "<6.5%",
        "D": "<7.5%",
        "答案": "B",
        "出处": "中国2型糖尿病防治指南(2020年版)，中华医学会糖尿病学分会",
    },
    {
        "题号":6,
        "维度":"指南",
        "题目": "根据《中国心力衰竭诊断和治疗指南2024》，慢性 HFrEF 基础治疗「新四联」不包括下列哪项？",
        "A": "维立西呱",
        "B": "β受体阻滞剂",
        "C": "醛固酮受体拮抗剂（MRA）",
        "D": "ARNI/ACEI",
        "答案": "A",
        "出处": "中国心力衰竭诊断和治疗指南2024（新四联=ARNI/ACEI+β受体阻滞剂+MRA+SGLT2i；维立西呱为特定患者加用）",
    },
    {
        "题号":7,
        "维度":"指南",
        "题目": "根据中国心房颤动诊疗指南，非瓣膜性房颤患者启动口服抗凝治疗的 CHA2DS2-VASc 评分界值为？",
        "A": "男性≥1分、女性≥2分",
        "B": "男性≥3分、女性≥4分",
        "C": "所有房颤患者均需抗凝",
        "D": "男性≥2分、女性≥3分",
        "答案": "D",
        "出处": "心房颤动诊断和治疗中国指南(2023)；CHA2DS2-VASc评分",
    },
    {
        "题号":8,
        "维度":"指南",
        "题目": "根据《中国高尿酸血症与痛风诊疗指南（2019）》，合并痛风石的痛风患者血尿酸控制目标为？",
        "A": "<300 μmol/L",
        "B": "<360 μmol/L",
        "C": "<420 μmol/L",
        "D": "<240 μmol/L",
        "答案": "A",
        "出处": "中国高尿酸血症与痛风诊疗指南(2019)，中华内分泌代谢杂志",
    },
    {
        "题号":9,
        "维度":"指南",
        "题目": "根据《中国幽门螺杆菌感染治疗指南（2022）》，Hp 感染初次根除治疗推荐的方案是？",
        "A": "PPI+两种抗生素三联疗法，疗程7天",
        "B": "铋剂四联方案（PPI+铋剂+两种抗生素），疗程14天",
        "C": "铋剂四联方案，疗程7天",
        "D": "高剂量双联方案，疗程7天",
        "答案": "B",
        "出处": "中国幽门螺杆菌感染治疗指南(2022)（铋剂四联14天：强推荐，中等质量）",
    },
    {
        "题号":10,
        "维度":"指南",
        "题目": "根据 GOLD 2024（慢性阻塞性肺疾病全球倡议），COPD 稳定期初始药物治疗首选为？",
        "A": "吸入糖皮质激素（ICS）单药",
        "B": "全身性糖皮质激素",
        "C": "长效支气管舒张剂（LABA和/或LAMA）",
        "D": "祛痰药物",
        "答案": "C",
        "出处": "GOLD 2024全球策略（初始治疗以支气管舒张剂为主，不鼓励ICS/LABA常规用于COPD）",
    },
    {
        "题号":11,
        "维度":"指南",
        "题目": "根据《中国2型糖尿病防治指南（2020年版）》采纳的流行病学调查，我国18岁及以上人群糖尿病患病率为？",
        "A": "9.7%",
        "B": "12.8%",
        "C": "13.7%",
        "D": "11.2%",
        "答案": "D",
        "出处": "中国2型糖尿病防治指南(2020年版)（2015-2017年全国调查，患病率11.2%）",
    },
    {
        "题号":12,
        "维度":"指南",
        "题目": "根据《中国高尿酸血症与痛风诊疗指南（2019）》，无合并症的痛风患者起始降尿酸药物治疗的血尿酸界值为？",
        "A": "≥420 μmol/L",
        "B": "≥480 μmol/L",
        "C": "≥360 μmol/L",
        "D": "≥540 μmol/L",
        "答案": "B",
        "出处": "中国高尿酸血症与痛风诊疗指南(2019)（血尿酸≥480启动；≥420且合并特定情况时启动）",
    },
]
df = pd.DataFrame(q_guideline)
df

,题号,维度,题目,A,B,C,D,答案,出处
0,1,指南,根据《中国高血压防治指南（2024年修订版）》，下列哪种情况可诊断高血压？,诊室血压≥130/80 mmHg,家庭自测血压≥135/85 mmHg,24小时动态血压平均值≥140/90 mmHg,仅凭单次诊室血压≥140/90 mmHg,B,中国高血压防治指南(2024年修订版)，中华高血压杂志2024年第7期
1,2,指南,根据2024年中国高血压防治指南，一般高血压患者的降压治疗目标是？,诊室血压<140/90 mmHg，如能耐受降至<130/80 mmHg,一律降至<130/80 mmHg,老年人一律<150/90 mmHg,一律降至<120/80 mmHg,A,中国高血压防治指南(2024年修订版)
2,3,指南,根据《中国血脂管理指南（2023年）》，ASCVD 极高危患者的 LDL-C 控制目标为？,<3.4 mmol/L,<2.6 mmol/L,<1.4 mmol/L 且较基线降低>50%,<1.8 mmol/L 且较基线降低>50%,D,中国血脂管理指南(2023年)，中国循环杂志2023;38(3)
3,4,指南,根据《中国血脂管理指南（2023年）》，ASCVD 超高危患者的 LDL-C 控制目标为？,<3.4 mmol/L,<2.6 mmol/L,<1.4 mmol/L 且较基线降低>50%,<1.8 mmol/L 且较基线降低>50%,C,中国血脂管理指南(2023年)
4,5,指南,根据《中国2型糖尿病防治指南（2020年版）》，一般成人2型糖尿病患者的 HbA1c 控制目标为？,<6.0%,<7.0%,<6.5%,<7.5%,B,中国2型糖尿病防治指南(2020年版)，中华医学会糖尿病学分会
5,6,指南,根据《中国心力衰竭诊断和治疗指南2024》，慢性 HFrEF 基础治疗「新四联」不包括下列哪项？,维立西呱,β受体阻滞剂,醛固酮受体拮抗剂（MRA）,ARNI/ACEI,A,中国心力衰竭诊断和治疗指南2024（新四联=ARNI/ACEI+β受体阻滞剂+MRA+SGL...
6,7,指南,根据中国心房颤动诊疗指南，非瓣膜性房颤患者启动口服抗凝治疗的 CHA2DS2-VASc 评分...,男性≥1分、女性≥2分,男性≥3分、女性≥4分,所有房颤患者均需抗凝,男性≥2分、女性≥3分,D,心房颤动诊断和治疗中国指南(2023)；CHA2DS2-VASc评分
7,8,指南,根据《中国高尿酸血症与痛风诊疗指南（2019）》，合并痛风石的痛风患者血尿酸控制目标为？,<300 μmol/L,<360 μmol/L,<420 μmol/L,<240 μmol/L,A,中国高尿酸血症与痛风诊疗指南(2019)，中华内分泌代谢杂志
8,9,指南,根据《中国幽门螺杆菌感染治疗指南（2022）》，Hp 感染初次根除治疗推荐的方案是？,PPI+两种抗生素三联疗法，疗程7天,铋剂四联方案（PPI+铋剂+两种抗生素），疗程14天,铋剂四联方案，疗程7天,高剂量双联方案，疗程7天,B,中国幽门螺杆菌感染治疗指南(2022)（铋剂四联14天：强推荐，中等质量）
9,10,指南,根据 GOLD 2024（慢性阻塞性肺疾病全球倡议），COPD 稳定期初始药物治疗首选为？,吸入糖皮质激素（ICS）单药,全身性糖皮质激素,长效支气管舒张剂（LABA和/或LAMA）,祛痰药物,C,GOLD 2024全球策略（初始治疗以支气管舒张剂为主，不鼓励ICS/LABA常规用于COPD）
10,11,指南,根据《中国2型糖尿病防治指南（2020年版）》采纳的流行病学调查，我国18岁及以上人群糖尿病...,9.7%,12.8%,13.7%,11.2%,D,中国2型糖尿病防治指南(2020年版)（2015-2017年全国调查，患病率11.2%）
11,12,指南,根据《中国高尿酸血症与痛风诊疗指南（2019）》，无合并症的痛风患者起始降尿酸药物治疗的血尿...,≥420 μmol/L,≥480 μmol/L,≥360 μmol/L,≥540 μmol/L,B,中国高尿酸血症与痛风诊疗指南(2019)（血尿酸≥480启动；≥420且合并特定情况时启动）

### 练习 4：伦理维度（12 题）

知情同意、隐私保护、临终关怀、医疗资源分配等伦理题（答案依据伦理规范）。

In [8]:
q_ethics=[
    {
        "题号":1,
        "维度":"伦理",
        "题目": "遗传咨询医师面向患者进行遗传咨询，以减少遗传病带给患者及其家庭的痛苦，帮助他们做出符合其最佳利益的决定。从伦理学视角分析，下列描述正确的是",
        "A": "咨询医师提出的意见应当是指令性的，因为咨询医师的意见是专业意见",
        "B": "咨询医师提出的意见应当是指令性的，因为咨询医师与患者的价值是一致的",
        "C": "咨询医师提出的意见应当是非指令性的，应该以患者的价值为中心",
        "D": "咨询医师提出的意见应当是非指令性的，应该以咨询医师的价值为中心",
        "答案": "C",
    },
    {
        "题号":2,
        "维度":"伦理",
        "题目": "临床医疗情境下，知情同意最重要的伦理意义是",
        "A": "充分尊重患者的自主性和医疗决策权，由患者本人做出有关其个人的医疗决策",
        "B": "对医疗中可能发生的种种风险和不适进行充分描述，因此有重要的医学防御意义",
        "C": "患者有义务询问对自己医疗干预的益处和风险，据此医生向患者提供相关信息",
        "D": "向患者提供帮其做出最佳决策的信息和医疗建议，获得患者许可并授权医生治疗",
        "答案": "D",
    },
    {
        "题号":3,
        "维度":"伦理",
        "题目": "在医患关系中，患者的健康信息属于保密范围，普遍认为对遗传信息也应当保密，只在特定情况下信息透露可以得到伦理学辩护。某女性检测出BRCA1基因突变，乳腺癌发病风险增高。医生下列做法恰当的是",
        "A": "建议该女性将此信息告知直系亲属",
        "B": "将该遗传信息透露给其应聘单位",
        "C": "将该信息透露给保险公司",
        "D": "将该信息直接透露给其全部家属",
        "答案": "A",
    },
    {
        "题号":4,
        "维度":"伦理",
        "题目": "男性，78岁。因脑梗死昏迷被家人送医院救治，治疗多日仍意识不清，家属要求放弃治疗。针对家属的要求，医生应当考虑的首要因素是",
        "A": "患者的社会地位",
        "B": "患者家属的意愿",
        "C": "患者的经济条件",
        "D": "患者的疾病状况",
        "答案": "D",
    },
    {
        "题号":5,
        "维度":"伦理",
        "题目": "女性，35岁。诊断为子宫肌瘤，需手术治疗。术中发现右侧卵巢有一个囊肿，可一并切除。这种情况下，医生与患者家属正确的沟通方式是",
        "A": "等做完手术后再与患者及家属说明",
        "B": "手术继续进行，派助手口头通知患者家属需扩大手术范围",
        "C": "先缝合手术切口，待与患者家属沟通好再行囊肿切除手术",
        "D": "立即与患者家属沟通，取得书面同意后行囊肿切除术",
        "答案": "D",
    },
    {
        "题号":6,
        "维度":"伦理",
        "题目": "辅助生殖技术是指代替自然生殖过程某些步骤的手段。根据临床伦理学的原则，关于医务人员的义务，下列观点正确的是",
        "A": "为不育夫妇提供出于个人偏好而选择胎儿性别的辅助生殖服务",
        "B": "为夫妇提供出于提升未来婴儿智力目的的辅助生殖服务",
        "C": "为单身女性提供捐赠精子或捐赠胚胎的辅助生殖服务",
        "D": "为不育夫妇提供与弥补正常功能障碍直接相关的辅助生殖服务",
        "答案": "D",
    },
    {
        "题号":7,
        "维度":"伦理",
        "题目": "干细胞研究已取得令人瞩目的成果，但其研究成果的临床转化必须具有重要的科学及社会价值。关于干细胞临床转化，下列最应优先考虑的理由是",
        "A": "国外类似产品已获批上市，国内产品也应尽快获批",
        "B": "为解决严重威胁患者生命且尚无有效干预的健康问题",
        "C": "该疗法适应证广阔、经济效益颇佳、患者热切期待",
        "D": "研究结果提示该干细胞制剂疗效可",
        "答案": "B",
    },
    {
        "题号":8,
        "维度":"伦理",
        "题目": "医学研究常常涉及使用患者的临床诊疗剩余血样，对此通用的伦理要求是获得患者明确的知情同意。下列不适用这一要求的情形是",
        "A": "使用诊疗剩余将要废弃的血样",
        "B": "使用诊疗剩余去除标识的血样",
        "C": "使用无法回溯来源的血样",
        "D": "使用经过加密编码的血样",
        "答案": "C",
    },
    {
        "题号":9,
        "维度":"伦理",
        "题目": "女，35岁。习惯性流产，经检查确诊为双角子宫，无法足月妊娠。患者要求医生对此信息保密，否则会破坏她的婚姻。医生的做法能够得到伦理学辩护的是",
        "A": "保护患者的隐私，不将患者的该信息透露给无关人员，包括其丈夫",
        "B": "拒绝患者的要求，因为该患者的丈夫有知情权",
        "C": "拒绝患者的要求，因为医生应该说真话",
        "D": "拒绝患者的要求，因为生育是夫妻双方的权利",
        "答案": "A",
    },
    {
        "题号":10,
        "维度":"伦理",
        "题目": "某医院急诊科凌晨2点接诊一名车祸昏迷患者，经诊断为颅内出血，需立即手术以挽救患者生命。此时无法联系到患者的近亲属或关系人，下列做法正确的是",
        "A": "经治医生可自行决定实施手术治疗",
        "B": "经医生所在科室主任同意后实施手术治疗",
        "C": "经医院负责人或被授权的负责人批准后实施手术治疗",
        "D": "经请示上级医疗机构主管部门批准后实施手术治疗",
        "答案": "C",
    },
    {
        "题号":11,
        "维度":"伦理",
        "题目": "《纽伦堡法典》是1946年审判纳粹战犯的纽伦堡军事法庭决议的一部分，涉及到人体试验的十个道德要求，其第一条是",
        "A": "试验应该立足于充分的动物实验已经获得的结果",
        "B": "试验的危险性不得超过试验目的的人道主义重要性",
        "C": "试验前获得受试者的自愿同意是绝对必要的",
        "D": "事先确信会发生死亡或残疾的试验",
        "答案": "C",
    },
    {
        "题号":12,
        "维度":"伦理",
        "题目": "根据临床试验的伦理学原则，以下叙述正确的是",
        "A": "试验设计应使受试者和社会均受益",
        "B": "试验设计应使受试者直接受益",
        "C": "临床试验设计受益风险比应该合理",
        "D": "受试者提出理由才允许其退出试验",
        "答案": "C",
    },
]
df = pd.DataFrame(q_ethics)
df

,题号,维度,题目,A,B,C,D,答案
0,1,伦理,遗传咨询医师面向患者进行遗传咨询，以减少遗传病带给患者及其家庭的痛苦，帮助他们做出符合其最佳...,咨询医师提出的意见应当是指令性的，因为咨询医师的意见是专业意见,咨询医师提出的意见应当是指令性的，因为咨询医师与患者的价值是一致的,咨询医师提出的意见应当是非指令性的，应该以患者的价值为中心,咨询医师提出的意见应当是非指令性的，应该以咨询医师的价值为中心,C
1,2,伦理,临床医疗情境下，知情同意最重要的伦理意义是,充分尊重患者的自主性和医疗决策权，由患者本人做出有关其个人的医疗决策,对医疗中可能发生的种种风险和不适进行充分描述，因此有重要的医学防御意义,患者有义务询问对自己医疗干预的益处和风险，据此医生向患者提供相关信息,向患者提供帮其做出最佳决策的信息和医疗建议，获得患者许可并授权医生治疗,D
2,3,伦理,在医患关系中，患者的健康信息属于保密范围，普遍认为对遗传信息也应当保密，只在特定情况下信息透...,建议该女性将此信息告知直系亲属,将该遗传信息透露给其应聘单位,将该信息透露给保险公司,将该信息直接透露给其全部家属,A
3,4,伦理,男性，78岁。因脑梗死昏迷被家人送医院救治，治疗多日仍意识不清，家属要求放弃治疗。针对家属的...,患者的社会地位,患者家属的意愿,患者的经济条件,患者的疾病状况,D
4,5,伦理,女性，35岁。诊断为子宫肌瘤，需手术治疗。术中发现右侧卵巢有一个囊肿，可一并切除。这种情况下...,等做完手术后再与患者及家属说明,手术继续进行，派助手口头通知患者家属需扩大手术范围,先缝合手术切口，待与患者家属沟通好再行囊肿切除手术,立即与患者家属沟通，取得书面同意后行囊肿切除术,D
5,6,伦理,辅助生殖技术是指代替自然生殖过程某些步骤的手段。根据临床伦理学的原则，关于医务人员的义务，下...,为不育夫妇提供出于个人偏好而选择胎儿性别的辅助生殖服务,为夫妇提供出于提升未来婴儿智力目的的辅助生殖服务,为单身女性提供捐赠精子或捐赠胚胎的辅助生殖服务,为不育夫妇提供与弥补正常功能障碍直接相关的辅助生殖服务,D
6,7,伦理,干细胞研究已取得令人瞩目的成果，但其研究成果的临床转化必须具有重要的科学及社会价值。关于干细...,国外类似产品已获批上市，国内产品也应尽快获批,为解决严重威胁患者生命且尚无有效干预的健康问题,该疗法适应证广阔、经济效益颇佳、患者热切期待,研究结果提示该干细胞制剂疗效可,B
7,8,伦理,医学研究常常涉及使用患者的临床诊疗剩余血样，对此通用的伦理要求是获得患者明确的知情同意。下列...,使用诊疗剩余将要废弃的血样,使用诊疗剩余去除标识的血样,使用无法回溯来源的血样,使用经过加密编码的血样,C
8,9,伦理,女，35岁。习惯性流产，经检查确诊为双角子宫，无法足月妊娠。患者要求医生对此信息保密，否则会...,保护患者的隐私，不将患者的该信息透露给无关人员，包括其丈夫,拒绝患者的要求，因为该患者的丈夫有知情权,拒绝患者的要求，因为医生应该说真话,拒绝患者的要求，因为生育是夫妻双方的权利,A
9,10,伦理,某医院急诊科凌晨2点接诊一名车祸昏迷患者，经诊断为颅内出血，需立即手术以挽救患者生命。此时无...,经治医生可自行决定实施手术治疗,经医生所在科室主任同意后实施手术治疗,经医院负责人或被授权的负责人批准后实施手术治疗,经请示上级医疗机构主管部门批准后实施手术治疗,C
10,11,伦理,《纽伦堡法典》是1946年审判纳粹战犯的纽伦堡军事法庭决议的一部分，涉及到人体试验的十个道德...,试验应该立足于充分的动物实验已经获得的结果,试验的危险性不得超过试验目的的人道主义重要性,试验前获得受试者的自愿同意是绝对必要的,事先确信会发生死亡或残疾的试验,C
11,12,伦理,根据临床试验的伦理学原则，以下叙述正确的是,试验设计应使受试者和社会均受益,试验设计应使受试者直接受益,临床试验设计受益风险比应该合理,受试者提出理由才允许其退出试验,C

## 5. 合并 + 保存（练习 5：检查点）

```python
all_q = q_diag + q_drug + q_guideline + q_ethics   # 列表相加
df = pd.DataFrame(all_q)
df.to_csv("eval_questions.csv", index=False, encoding="utf-8-sig")
df["维度"].value_counts()      # 检查每维度题数
```

In [7]:
# 在这里写你的代码
all_q=q_diag + q_drug + q_guideline + q_ethics
df = pd.DataFrame(all_q)
df.to_csv("eval_questions.csv", index=False, encoding="utf-8-sig")
df["维度"].value_counts()

维度
诊断    12
用药    12
指南    12
伦理    12
Name: count, dtype: int64

## ✅ D20 完成标准（打钩）

- [ ] 4 个维度的题都写完（40-50 题）
- [ ] 每题的答案自己核验过
- [ ] 练习 5 合并成功，CSV 已保存
- [ ] 保存 notebook（**Cmd + S**）

完成后喊我验收。D21 跑评测：把题目喂给 DeepSeek，按你的打分标准评分，算每维度得分 + 幻觉统计。